---
<% chef_versions = %w( 16 ) %>
<% platforms = %w( centos-6 centos-7 ) %>
<% aem_versions = %w( 6.1.0 6.2.0 6.3.0 6.4.0 ) %>

driver:
  name: vagrant
  customize:
    memory: 3072

provisioner:
  name: chef_zero
  log_level: <%= ENV['TK_CHEF_LOG_LEVEL'] || 'info' %>
  data_path: test/shared

platforms:
<% platforms.each do |p| %>
<%   chef_versions.each do |chef_version| %>
  - name: <%= p %>-chef-<%= chef_version %>
    driver:
      linked_clone: true
    driver_config:
      box: bento/<%= p %>
      require_chef_omnibus: <%= chef_version %>
    attributes:
      cq:
        http_read_timeout: 900
        license:
          url: <%= ENV['CQ_LICENSE_URL'] %>
        packages:
          aem61:
            sp2: <%= ENV['CQ_V610_SP2_URL'] %>
            sp2_cfp3: <%= ENV['CQ_V610_SP2_CFP3_URL'] %>
      java:
        jdk:
          '8':
            x86_64:
              url: <%= ENV['JAVA_JDK_8_X86_64_URL'] || 'http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jdk-8u162-linux-x64.tar.gz' %>
              checksum: <%= ENV['JAVA_JDK_8_X86_64_CHECKSUM'] || '68ec82d47fd9c2b8eb84225b6db398a72008285fafc98631b1ff8d2229680257' %>
<%   end %>
<% end %>

suites:
  - name: commons
    run_list:
      - recipe[cq::default]
      - recipe[cq::commons]
  - name: commons-customized
    run_list:
      - recipe[cq::default]
      - recipe[cq::commons]
    attributes:
      cq:
        user: 'aem'
        user_uid: 200
        user_comment: 'Adobe AEM'
        user_shell: '/bin/sh'
        group: 'aem'
        group_gid: 200
        home_dir: '/opt/aem'

<% aem_versions.each do |v| %>

  <% short_ver = v.delete('.') %>
  <% url_var = "CQ_V#{short_ver}_JAR_URL" %>

  - name: aem<%= short_ver %>-author
    run_list:
      - recipe[cq::author]
      # - recipe[cq<%= short_ver %>::author_cq_package]
      # - recipe[cq<%= short_ver %>::author_cq_osgi_config]
      # - recipe[cq<%= short_ver %>::author_cq_osgi_bundle]
      # - recipe[cq<%= short_ver %>::author_cq_osgi_component]
      # - recipe[cq<%= short_ver %>::author_cq_user]
      # - recipe[cq<%= short_ver %>::author_cq_jcr]
      # - recipe[cq<%= short_ver %>::author_cq_clientlib_cache]
    attributes:
      cq:
        version: <%= v %>
        jar:
          url: <%= ENV[url_var] %>
  - name: aem<%= short_ver %>-publish
    run_list:
      - recipe[cq::publish]
      - recipe[cq<%= short_ver %>::publish_cq_user]
    attributes:
      cq:
        version: <%= v %>
        jar:
          url: <%= ENV[url_var] %>
<% end %>
